version: "3.9"
networks:
  int_network:

services:
    db:
        
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - int_network
        environment:
            SA_PASSWORD: Your_password123
            ACCEPT_EULA: Y
        ports:
            - 1433:1433
        volumes:
         - ./sqlserver/data:/var/opt/mssql/data
         - ./sqlserver/log:/var/opt/mssql/log
         

    databaseapp:
        image: uylyon/databaseapi:latest
        depends_on:
            - db
        restart: always
        ports:
            - 49151:443
            - 49150:80
        networks:
            - int_network
        environment:
            - databaseconnection=Server=db;Database=Master;User=SA;Password=Your_password123;
        links:
            - db
        deploy:
            replicas: 1

    clientapp:
        image: uylyon/clientapi:latest
        ports:
            - 49161:443
            - 49160:80
        networks:
            - int_network
        environment:
            - dataBaseAddress=http://databaseapp/DataBase/
        deploy:
            replicas: 1
        links:
            - databaseapp
        depends_on:
            - db
            - databaseapp